-- Global utility functions
-- @module utils

-- Catppuccin Mocha Palette 
-- @return table
function get_mocha() 
  return require("catppuccin.palettes").get_palette "mocha"
end

-- Custom Palette --
local colors = {
	rosewater = "#f5e0dc",
	flamingo = "#f2cdcd",
	pink = "#f5c2e7",
	mauve = "#cba6f7",
	red = "#f38ba8",
	maroon = "#eba0ac",
	peach = "#fab387",
	yellow = "#f9e2af",
	green = "#a6e3a1",
	teal = "#94e2d5",
	sky = "#89dceb",
	sapphire = "#74c7ec",
	blue = "#89b4fa",
	lavender = "#b4befe",
	text = "#cdd6f4",
	subtext1 = "#bac2de",
	subtext0 = "#a6adc8",
	overlay2 = "#9399b2",
	overlay1 = "#7f849c",
	overlay0 = "#6c7086",
	surface2 = "#585b70",
	surface1 = "#45475a",
	surface0 = "#313244",
	base = "#1e1e2e",
	mantle = "#181825",
	crust = "#11111b",
}

-- Custom Icons --
local icons = {
    kind = {
      Array = "",
      Boolean = "",
      Class = "",
      Color = "",
      Constant = "",
      Constructor = "",
      Enum = "",
      EnumMember = "",
      Event = "",
      Field = "",
      File = "",
      Folder = "",
      Function = "",
      Interface = "",
      Key = "",
      Keyword = "",
      Method = "",
      Module = "",
      Namespace = "",
      Null = "ﳠ",
      Number = "",
      Object = "",
      Operator = "",
      Package = "",
      Property = "",
      Reference = "",
      Snippet = "",
      String = "",
      Struct = "",
      Text = "",
      TypeParameter = "",
      Unit = "",
      Value = "",
      Variable = "",
    },
    git = {
      LineAdded = "",
      LineModified = "",
      LineRemoved = "",
      FileDeleted = "",
      FileIgnored = "◌",
      FileRenamed = "",
      FileStaged = "S",
      FileUnmerged = "",
      FileUnstaged = "",
      FileUntracked = "U",
      Diff = "",
      Repo = "",
      Octoface = "",
      Branch = "",
    },
    ui = {
      ArrowCircleDown = "",
      ArrowCircleLeft = "",
      ArrowCircleRight = "",
      ArrowCircleUp = "",
      BoldArrowDown = "",
      BoldArrowLeft = "",
      BoldArrowRight = "",
      BoldArrowUp = "",
      BoldClose = "",
      BoldDividerLeft = "",
      BoldDividerRight = "",
      BoldLineLeft = "▎",
      BookMark = "",
      BoxChecked = "",
      Bug = "",
      Stacks = "",
      Scopes = "",
      Watches = "",
      DebugConsole = "",
      Calendar = "",
      Check = "",
      ChevronRight = ">",
      ChevronShortDown = "",
      ChevronShortLeft = "",
      ChevronShortRight = "",
      ChevronShortUp = "",
      Circle = "",
      Close = "",
      CloudDownload = "",
      Code = "",
      Comment = "",
      Dashboard = "",
      DividerLeft = "",
      DividerRight = "",
      DoubleChevronRight = "»",
      Ellipsis = "",
      EmptyFolder = "",
      EmptyFolderOpen = "",
      File = "",
      FileSymlink = "",
      Files = "",
      FindFile = "",
      FindText = "",
      Fire = "",
      Folder = "",
      FolderOpen = "",
      FolderSymlink = "",
      Forward = "",
      Gear = "",
      History = "",
      Lightbulb = "",
      LineLeft = "▏",
      LineMiddle = "│",
      List = "",
      Lock = "",
      NewFile = "",
      Note = "",
      Package = "",
      Pencil = "",
      Plus = "",
      Project = "",
      Search = "",
      SignIn = "",
      SignOut = "",
      Tab = "",
      Table = "",
      Target = "󰀘",
      Telescope = "",
      Text = "",
      Tree = "",
      Triangle = "契",
      TriangleShortArrowDown = "",
      TriangleShortArrowLeft = "",
      TriangleShortArrowRight = "",
      TriangleShortArrowUp = "",
    },
    diagnostics = {
      BoldError = "",
      Error = "",
      BoldWarning = "",
      Warning = "",
      BoldInformation = "",
      Information = "",
      BoldQuestion = "",
      Question = "",
      BoldHint = "",
      Hint = "",
      Debug = "",
      Trace = "✎",
    },
    misc = {
      Robot = "ﮧ",
      Squirrel = "",
      Tag = "",
      Watch = "",
      Smiley = "",
      Package = "",
      CircuitBoard = "",
    },
  }


return {
  colors = colors,
  icons = icons,
}
